# Generated by Django 3.1.7 on 2021-04-08 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classroom.course'),
        ),
    ]
