# Generated by Django 3.1.7 on 2021-04-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20210406_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Student Attendance'},
        ),
        migrations.AlterModelOptions(
            name='courseenrolled',
            options={'verbose_name': 'Courses Enrolled'},
        ),
    ]
