# Generated by Django 3.1.7 on 2021-04-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20210406_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='isTeacher',
        ),
    ]
