# Generated by Django 3.1.7 on 2021-04-09 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=4, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
