# Generated by Django 3.1.7 on 2021-04-06 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_remove_myuser_isteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=4, validators=[django.core.validators.MinValueValidator(5.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2000-05-05'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='phNo',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='srn',
            field=models.CharField(default='PES1201800000', max_length=13, primary_key=True, serialize=False, verbose_name='SRN'),
        ),
    ]
