# Generated by Django 3.1.7 on 2021-04-06 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20210406_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='teacher@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phNo',
            field=models.CharField(default='0000000000', max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Phone No.'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='regNo',
            field=models.CharField(default='PES12018T0000', max_length=10, primary_key=True, serialize=False, verbose_name='Reg No'),
        ),
    ]
