# Generated by Django 3.1.7 on 2021-04-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_auto_20210406_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
